import fs from 'node:fs';

export const tshirtDataBase = [
  {
    id: '1',
    name: 'Cotton long sleeve T-shirt',
    category: 'woman',
    color: 'black',
    size: ['xs', 's', 'l', 'm'],
    price: '34€',
  },
  {
    id: '2',
    name: 'Cotton linen-blend T-shirt',
    category: 'woman',
    color: 'grey',
    size: ['s', 'l', 'm', 'xxl'],
    price: '27€',
  },
  {
    id: '3',
    name: 'Cotton basic  T-shirt',
    category: 'man',
    color: 'orange',
    size: ['xs', 's', 'm', 'xxl'],
    price: '30€',
  },
  {
    id: '4',
    name: 'Cotton long sleeve T-shirt',
    category: 'woman',
    color: 'pink',
    size: ['m', 'l', 'xxl'],
    price: '48€',
  },
  {
    id: '5',
    name: 'Essential long sleeve T-shirt',
    category: 'woman',
    color: 'red',
    size: ['xs', 's'],
    price: '45€',
  },
  {
    id: '6',
    name: 'Cotton linen-blend T-shirt',
    category: 'man',
    color: 'black',
    size: ['m', 'l', 'xl', 'xxl'],
    price: '28€',
  },
  {
    id: '7',
    name: 'Cotton long-sleeve',
    category: 'man',
    color: 'white',
    size: ['xs', 's', 'm'],
    price: '31€',
  },
  {
    id: '8',
    name: 'Premium Cotton T-shirt',
    category: 'man',
    color: 'orange',
    size: ['xs', 's', 'm', 'l', 'xxl'],
    price: '25€',
  },
  {
    id: '9',
    name: 'Ladies`Basic-T-shirt',
    category: 'woman',
    color: 'brown',
    size: ['s', 'l', 'xxl'],
    price: '30€',
  },
];
